---

- name: Install pgbouncer
  yum:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - pgbouncer

# Or edit with linefile?
- name: Copy pgbouncer.ini template 
  template: owner=root group=root mode=644 
            src=pgbouncer.ini
            dest=/etc/pgbouncer/pgbouncer.ini
  notify:
    - reload pgbouncer

- name: Start pgbouncer
  service: 
    name: pgbouncer 
    state: started
    enabled: yes 

...

