---

# https://github.com/Lelik13a/Zabbix-PyOra-ActiveCheck

- name: git clone plpgsql_check  
  git:
    repo: https://github.com/Lelik13a/Zabbix-PyOra-ActiveCheck.git
    dest: /tmp/Zabbix-PyOra-ActiveCheck
    update: yes

# Create Oracle user for Pyora usage
# oracle instantclienti - as role dependansy
- name: "Install cx_Oracle"
  pip:
    name: cx-Oracle
# c. https://github.com/blacked/py-zabbix
- name: "Install py-zabbix"
  pip:
    name: py-zabbix

# d. zabbix agent - ?

#3. Copy externalscripts/* to /usr/lib/zabbix/externalscripts/
- name: "Copy externalscripts/* to /usr/lib/zabbix/externalscripts/"
  copy:
    src: /tmp/Zabbix-PyOra-ActiveCheck/externalscripts
    dest: /usr/lib/zabbix/externalscripts
    remote_src: yes

#4. Edit /usr/lib/zabbix/externalscripts/pyora_config.py

- name: "Copy zabbix_agentd.d/oracle_pyora.conf to /etc/zabbix/zabbix_agentd.d/ and restart zabbix agent"
  copy:
    src: /tmp/Zabbix-PyOra-ActiveCheck/zabbix_agentd.d/oracle_pyora.conf
    dest: /etc/zabbix/zabbix_agentd.d/oracle_pyora.conf
    remote_src: yes
  #notify: restart zabbix-agent

- name:  Create directory which will be contains items list for every database.
  file: 
    path: /usr/lib/zabbix/cache
    owner: zabbix
    group: zabbix
    state: directory

#7. Import to zabbix "Template Pyora active send".
#8. Create via zabbix web interface host, from which the checks will be performed.
#Fill macros:
# use zabbix_hostmacro

#9. Create cron job with databases parameters, like:
- name: "Create cron job with databases parameters."
  cron:
    name: "pgbadber daily"
    user: zabbix
    minute: "10"
    job: "/usr/lib/zabbix/externalscripts/pyora-active.py  --address database_address --database database_SID"

...
