---

# https://github.com/Lelik13a/Zabbix-PyOra-ActiveCheck

- name: git clone plpgsql_check  
  git:
    repo: https://github.com/Lelik13a/Zabbix-PyOra-ActiveCheck.git
    dest: /tmp/Zabbix-PyOra-ActiveCheck
    update: yes

# Create Oracle user for Pyora usage

# oracle instantclient - as role dependansy

- name: "Install cx_Oracle"
  pip:
    name: cx-Oracle

- name: "Install py-zabbix"
  pip:
    name: py-zabbix

# d. zabbix agent - ?

# Copy externalscripts/* to /usr/lib/zabbix/externalscripts/
# Is there a way to copy it recursively?

- name: Create directory for external scripts.
  file:
    path: /usr/lib/zabbix/externalscripts/
    owner: zabbix
    group: zabbix
    state: directory

- name: "Copy pyora-active.py to /usr/lib/zabbix/externalscripts/"
  copy:
    src: /tmp/Zabbix-PyOra-ActiveCheck/externalscripts/pyora-active.py
    dest: /usr/lib/zabbix/externalscripts/
    remote_src: yes
    owner: zabbix
    group: zabbix
    mode: 0644

- name: "Copy pyora-discovery.py to /usr/lib/zabbix/externalscripts/"
  copy:
    src: /tmp/Zabbix-PyOra-ActiveCheck/externalscripts/pyora-discovery.py
    dest: /usr/lib/zabbix/externalscripts/pyora-discovery.py
    remote_src: yes
    owner: zabbix
    group: zabbix
    mode: 0644

- name: "Copy pyora-items-list.py to /usr/lib/zabbix/externalscripts/"
  copy:
    src: /tmp/Zabbix-PyOra-ActiveCheck/externalscripts/pyora-items-list.py
    dest: /usr/lib/zabbix/externalscripts/pyora-items-list.py
    remote_src: yes
    owner: zabbix
    group: zabbix
    mode: 0644


#4. Edit /usr/lib/zabbix/externalscripts/pyora_config.py

- name: "Copy zabbix_agentd.d/oracle_pyora.conf to /etc/zabbix/zabbix_agentd.d/ and restart zabbix agent"
  copy:
    src: /tmp/Zabbix-PyOra-ActiveCheck/zabbix_agentd.d/oracle_pyora.conf
    dest: /etc/zabbix/zabbix_agentd.d/oracle_pyora.conf
    remote_src: yes
  #notify: restart zabbix-agent

- name:  Create directory which will be contains items list for every database.
  file: 
    path: /usr/lib/zabbix/cache
    owner: zabbix
    group: zabbix
    state: directory

#7. Import Template Pyora active send to zabbix server. Skip for now
#8. Create via zabbix web interface host, from which the checks will be performed. Skip for now

#Fill macros:
# use ansible zabbix_hostmacro

#9. Create cron job with databases parameters, like:
- name: "Create cron job with databases parameters."
  cron:
    name: "pyora-active every 10 minutes"
    user: zabbix
    minute: "10"
    job: "/usr/lib/zabbix/externalscripts/pyora-active.py  --address {{ ansible_hostname }} --database SID"

...
