---

- name: Add firewall exception for ceph-mon.
  firewalld: service=ceph-mon permanent=true state=enabled immediate=yes

- name: Add firewall exception for ceph.
  firewalld: service=ceph permanent=true state=enabled immediate=yes

...