- name: download repo file 
  shell: for x in {1..3}; do wget -O /tmp/pgdg{{ postgresql_version | replace('.', '') }}.rpm https://yum.postgresql.org/{{ postgresql_version }}/redhat/rhel-7-x86_64/pgdg-{{ ansible_distribution | lower }}{{ postgresql_version | replace('.','') }}-{{ postgresql_version }}-$x.noarch.rpm && break; done
  tags: pgdg

- name: Add pgdg repository
  yum:
    name: /tmp/pgdg{{ postgresql_version | replace('.', '') }}.rpm
    state: present
  tags: pgdg

- name: update repository
  yum: 
    name: 'pgdg*'
    state: latest
  tags: pgdg

