---
galaxy_info:
   author: Daniil Aksenov(dbax)
   description: Deploy etcd cluster
   company: dbax
   license: GPLv2
   min_ansible_version: 2.9

   platforms:
      - name: Centos
        versions:
           - 7

   galaxy_tags: [etcd]

dependencies: []
