---
- name: Install HAProxy
  yum: 
    name: haproxy
    state: latest

- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy
