---
galaxy_info:
  author: Daniil Aksenov
  description: Atop installation and confuguration
  license: as-is

  min_ansible_version: 2.9

  platforms:
    - name: centos
      versions:
        - 7

  galaxy_tags:
    - atop
    - monitoring

dependencies: []
