---
# postgresql.conf settings as required on http://dalibo.github.io/pgbadger/

- name: Modify postgresql.conf log_line_prefix.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_line_prefix ="
      line: "log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '"
  
- name: Modify postgresql.conf log_min_duration_statement.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_min_duration_statement ="
      line: "log_min_duration_statement = 0"
  
- name: Modify postgresql.conf log_checkpoints.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_checkpoints ="
      line: "log_checkpoints = on"
  
- name: Modify postgresql.conf log_connections.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_connections ="
      line: "log_connections = on"

- name: Modify postgresql.conf log_disconnections.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_disconnections ="
      line: "log_disconnections = on"
  
- name: Modify postgresql.conf log_lock_waits.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_lock_waits ="
      line: "log_lock_waits = on"

- name: Modify postgresql.conf log_temp_files.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_temp_files ="
      line: "log_temp_files = 0"

- name: Modify postgresql.conf log_autovacuum_min_duration.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_autovacuum_min_duration ="
      line: "log_autovacuum_min_duration = 0"

- name: Modify postgresql.conf log_error_verbosity.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_error_verbosity ="
      line: "log_error_verbosity = default"

- name: Modify postgresql.conf lc_messages.
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?lc_messages ="
      line: "lc_messages = 'C'"

...