---

- name: Modify postgresql.conf log_line_prefix
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_line_prefix ="
      line: "log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '"
  notify: reload postgres

- name: Modify postgresql.conf log_min_duration_statement
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "^#?log_min_duration_statement ="
      line: "log_min_duration_statement = 0"
  notify: reload postgres


#log_checkpoints = on
#log_connections = on
#log_disconnections = on
#log_lock_waits = on
#log_temp_files = 0
#log_autovacuum_min_duration = 0
#log_error_verbosity = default
#lc_messages='C'


...