---

- name: Modify postgresql.conf log_line_prefix
  lineinfile:
      dest: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
      regexp: "#.log_line_prefix="
      line: "log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '"
  notify: reload postgres

...