---
galaxy_info:
  author: Daniil Aksenov(dbax)
  description: Postgresql installation and setup with Patroni HA.
  company: dbax
  license: as-is

  min_ansible_version: 2.9
  platforms:
    - name: Centos
      versions:
        - 7

  galaxy_tags: [postgresql]

dependencies: []
