---

- name: Accign current ip as static.
  template: owner=root group=root mode=644 
            src=ifcfg-interface 
            dest=/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
            backup=yes
  notify: restart network
 
- name: Reminder.
  debug:
     msg: Do not forget to exclude "{{ ansible_default_ipv4.address }}" from dhcp!

...
