---

- name: Set specific routes for default interface. temporary solution
  lineinfile:
    path: /etc/sysconfig/network-scripts/route-{{ ansible_default_ipv4.interface }}
    line: '192.168.192.0/24 via 192.168.154.178'
    create: yes
    state: present
  notify: restart network

...
