---

- name: Ensure rsyslog package is installed.
  yum: 
    name:
      - rsyslog

- name: Forward logs to syslog servers.
  template: owner=root group=root mode=644
            src=rsyslog_client.conf
            dest=/etc/rsyslog.d/rsyslog_client.conf
  notify: restart rsyslog  

...
