---
- hosts: all
  remote_user: "{{ my_ansible_user }}"
  become: yes 

  roles:
    - proxy_settings
    - essentials
    - hostname
    - selinux
    - yum-update
    - zabbix-agent
    - ntpd

   # Fix, tune and add this to into play.
   #- add_admin
   #- sshd

   #  Needs to be fixed and revorked.
   #- postfix

  environment:
    http_proxy: "{{ proxy_ip }}"
    https_proxy: "{{ proxy_ip }}"
