---

- hosts: postgres 
  user: {{ my_ansible_user }}
  become: yes

  roles:
      - pgagent
      - oraclefdw
      - plpgsql_check
      - barman
      - pg_dumps

  vars:
     local_path: "{{ lookup('env','PATH') }}"

  environment:
    PATH: "{{ local_path }}:/usr/pgsql-{{ postgresql_version }}/bin"

...
