---
- hosts: postgres
  remote_user: "{{ my_ansible_user }}"
  become: yes
  roles:
   - postgres_repo
   - postgres_install
   - postgres_patroni
   #- postgres_powa
   - pgbouncer
   #- postgres_mamonsu