---

- hosts: postgres 
  user: "{{ my_ansible_user }}"
  become: yes

  roles:
      - postgres_repository
      - postgres_install 
      - postgres_config
      - postgres_mamonsu
      - postgres_pgbouncer
      - postgres_pgbadger
      - postgres_utils

  vars:
     local_path: "{{ lookup('env','PATH') }}"
     postgresql_distribution: "postgrespro"

  environment:
     PATH: "{{ local_path }}:/usr/pgpro-{{ postgresql_version }}/bin"
     http_proxy: "{{ proxy_ip }}"
     https_proxy: "{{ proxy_ip }}"


...
