---
- name: Bring up docker containers
  hosts: localhost
  become: yes
  gather_facts: false
  vars:
    inventory:
      - name: iptables_host_1
        image: "chrismeyers/centos7"
  roles:
    - { role: provision_docker, provision_docker_inventory: "{{inventory}}" }


- name: Hello world
  hosts: docker_containers
  tasks:
    - debug: msg="Hello World"

