---

- name: copy oracle client from local repo
  copy: src={{ item }} 
        dest=/tmp
  with_items:
        - ~/localrepo/oracle-instantclient{{ ora_version | truncate(4,False,"") }}-basic-{{ ora_version }}.x86_64.rpm
        - ~/localrepo/oracle-instantclient{{ ora_version | truncate(4,False,"") }}-devel-{{ ora_version }}.x86_64.rpm 
        - ~/localrepo/oracle-instantclient{{ ora_version | truncate(4,False,"") }}-sqlplus-{{ ora_version }}.x86_64.rpm
        - ~/localrepo/oracle-instantclient{{ ora_version | truncate(4,False,"") }}-odbc-{{ ora_version }}.x86_64.rpm

- name: install client packages
  yum: name={{ item }}
  with_items: 
        - /tmp/oracle-instantclient{{ ora_version | truncate(4,False,"") }}-basic-{{ ora_version }}.x86_64.rpm
        - /tmp/oracle-instantclient{{ ora_version | truncate(4,False,"") }}-devel-{{ ora_version }}.x86_64.rpm
        - /tmp/oracle-instantclient{{ ora_version | truncate(4,False,"") }}-sqlplus-{{ ora_version }}.x86_64.rpm
        - /tmp/oracle-instantclient{{ ora_version | truncate(4,False,"") }}-odbc-{{ ora_version }}.x86_64.rpm

- name: Add oracle library.
  lineinfile:
    dest: "/etc/ld.so.conf.d/oracle.conf"
    state: present
    line: "/usr/lib/oracle/11.2/client64/lib"
    create: yes

- name: Run ldconfig to register libs.
  shell: ldconfig

...
