galaxy_info:
  author: "Daniil Aksenov"
  description: A role to install Postgresql wait_sampling extension.
  license: as-is
  platforms:
    - name: EL
      versions:
      - 7 mostly
  categories:
   - database
   - database:sql

