- name: Installing packages
  yum: name={{ item }}
  with_items:
      - gcc
      - make

- name: Download oracle client stuff
  get_url: url={{ item }} dest=/tmp use_proxy=192.168.154.42:48080
  with_items: 
        - http://download.oracle.com/otn/linux/instantclient/121020/oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
        - http://download.oracle.com/otn/linux/instantclient/121020/oracle-instantclient12.1-sqlplus-12.1.0.2.0-1.x86_64.rpm
        - http://download.oracle.com/otn/linux/instantclient/121020/oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm

#- name: Set variables
# pg_config
# LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib

- name: git clone oraclefdw 
  git: repo=https://github.com/laurenz/oracle_fdw
       dest=/tmp/oracle_fdw
       update=yes

- name: make oracle_fdw
  shell: make && make install 
  args:
    chdir: /tmp/oracle_fdw
