- name: Installing packages
  yum: name={{ item }}
  with_items:
      - gcc
      - make

#- name: Set variables
# pg_config //do we need it?
# LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
# ldconfig comehow


- name: git clone oraclefdw 
  git: repo=https://github.com/laurenz/oracle_fdw
       dest=/tmp/oracle_fdw
       update=yes

- name: make oracle_fdw
  shell: make && make install 
  args:
    chdir: /tmp/oracle_fdw

#psql -U postgres
#CREATE EXTENSION oracle_fdw;

