---

- name: Installing packages.
  yum: 
    name:
      - mailx
      - postfix
      - cyrus-sasl
      - cyrus-sasl-plain

- name: Setup main.cf from template.
  template:
    src: main.cf.j2
    dest: "/etc/postfix/main.cf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart postfix

- name: Setup sasl_password from template.
  template:
    src: sasl_password.js
    dest: "/etc/postfix/sasl_password"
    owner: root
    group: root
    mode: 0600
  notify: restart postfix

- name: ensure sasl_password is compiled
    shell: postmap /etc/postfix/sasl_passwd
  notify: restart postfix

- name: Start and enable postfix.
  systemd: 
    name: postfix
    enabled: yes 
    state: started

...
