---

#- name: Copy google.com certificate.
#  copy: src={{ item }} 
#        dest=/etc/postfix/certs/
#  with_items:
#        - ~/localrepo/google.com.cer  

- name: Copy google.com certificate.
  copy: src={{ item }} 
        dest=/etc/postfix/
  with_items:
        - ~/localrepo/sasl_password  

- name: Edit config file. Set mailbox_size_limit to 0.
  lineinfile: dest=/etc/postfix/main.cf line='smtp_sasl_password_maps = hash:/etc/postfix/sasl_password'
  notify: restart postfix


#- name: Setup mailing user.
#  template: owner=root group=root mode=644 
#            src=sasl_password.js
#            dest=/etc/postfix/sasl_password

...
