- name: Installing packages
  yum: name={{ item }}
  with_items:
      - mailx
      - postfix

- lineinfile: dest=/etc/postfix/main.cf line='relayhost = {{ smtp_server }}:{{ smtp_port }}'

- systemd: 
    name: postfix
    enabled: yes 
    state: started

