- name: "install repository package"
  shell: yum localinstall -y http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
  #yum: 
  #  state: present
  #  name: http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
  tags: zabbix-agent

- name: "install zabbix-agent"
  yum: 
    state: latest
    pkg: "{{ item }}"
  with_items:
    - zabbix-agent
  tags: zabbix-agent

- name: edit agent.conf file
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server=*' line='Server=192.168.154.145'
  tags: zabbix-agent
  notify: restart agent
  
- name: edit agent.conf file
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=*' line='Hostname={{ ansible_hostname }}'
  tags: zabbix-agent
  notify: restart agent


- name: "start agent"
  service: name=zabbix-agent state=started enabled=yes 
  tags: zabbix-agent

- name: add firewall exception
  firewalld: port=10050/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  tags: zabbix-agent
