---
- name: Enable zabbix yum repository.
  yum_repository:
    name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
    gpgcheck: true
    enabled: true
  when: ansible_pkg_mgr == 'yum'

- name: Yum install zabbix-agent
  yum:
    state: present
    name:
      - zabbix-agent
      - zabbix-get
      - zabbix-sender
  when: ansible_pkg_mgr == 'yum'

- name: Template configs
  template:
      src: zabbix_agentd.conf.j2
      dest: "/etc/zabbix/zabbix_agentd.conf"
      owner: "zabbix"
      group: "zabbix"
      backup: true
  notify: restart agent

- name: Start and enable agent
  service:
    name: zabbix-agent
    state: started
    enabled: true

- name: Add firewall exception. Ignore on errors(if firewall is disabled)
  firewalld:
    port: 10050/tcp
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true
