---

- name: Enable zabbix repository.
  yum_repository:
    name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: http://repo.zabbix.com/zabbix/3.2/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
    gpgcheck: yes
    enabled: yes

- name: Install zabbix-agent.
  yum: 
    state: latest
    pkg: "{{ item }}"
  with_items:
    - zabbix-agent

- name: Edit agent.conf file.
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server=*' line='Server={{ zabbix_server }}'
  notify: restart agent
  
- name: Edit agent.conf file.
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=*' line='Hostname={{ ansible_hostname }}'
  notify: restart agent

- name: Start and enable agent.
  service: name=zabbix-agent state=started enabled=yes 

- name: Add firewall exception. If firewall is on.
  firewalld: port=10050/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

...
