---
- name: Install zabbix-api pythons package on ansible host.
  local_action:
    module: pip
    name: zabbix-api
  run_once: true

- name: Set zabbix-agent name.
  set_fact:
     agent_name: "{{ inventory_hostname }}"   
     when: ansible_dns.search[0] is undefined

- name: Set zabbix-agent name.
  set_fact:
     agent_name: "{{ inventory_hostname }}.{{ ansible_dns.search[0] }}"   
     when: ansible_dns.search[0] is defined
  ignore_errors: True
  # find nicer way to escape it.

- name: Create zabbix host group.
  local_action:
    module: zabbix_group
    server_url: "{{ zabbix_url }}"
    login_user: Admin
    login_password: zabbix
    state: present
    host_groups:
      - "{{ zabbix_group }}"
  run_once: True
 
- name: Create new or update existing zabbix host. 
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: Admin
    login_password: zabbix
    host_name: "{{ agent_name }}"
    visible_name: "{{ agent_name }}"
    host_groups:
      - Linux servers
      - "{{ zabbix_group }}"
    link_templates:
      - Template OS Linux
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: "{{ agent_name }}"
        port: 10050
    proxy: "{{ zabbix_proxy }}"
