---
- name: Install zabbix-api pythons package on ansible host.
  local_action:
    module: pip
    name: zabbix-api
  run_once: true

- name: Create zabbix host group.
  local_action:
    module: zabbix_group
    server_url: "{{ zabbix_url }}"
    login_user: Admin
    login_password: zabbix
    state: present
    host_groups:
      - "{{ zabbix_group }}"
  run_once: True
 
- name: Create new or update existing zabbix host. 
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: Admin
    login_password: zabbix
    host_name: "{{ ansible_hostname }}"
    visible_name: "{{ ansible_hostname }}"
    host_groups:
      - Linux servers
      - "{{ zabbix_group }}"
    link_templates:
      - Template OS Linux
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: "{{ ansible_hostname }}"
        port: 10050
    proxy: "{{ zabbix_proxy }}"
