---
- name: Get current master 
  #command: stolonctl status --cluster-name {{ cluster_name }}  --store-backend consul --store-endpoints {{ store_endpoint }} -f json
  command: stolonctl status --cluster-name sp03_db_business_shard_01   --store-backend consul --store-endpoints https://consul-cluster-stage1.test.pcbl.local:8501 -f json
  
  become: true
  become_user: postgres
  register: stolon_output

- debug: 
    msg: "{{ stolon_output.cluster.master_keeper_uid }}"

- name: Set master
  set_fact: stolon_master = "{{ stolon_output.stdout | from_json }}"

#- name: Download backup
# when: "{{ ansible_hostname }}" == "{{ master_node }}"

#- name: Dump roles
# when: "{{ ansible_hostname }}" == "{{ master_node }}"
#- name: Dump db_links
# when: "{{ ansible_hostname }}" == "{{ master_node }}"

#- name: Stop stolon slaves
# when: "{{ ansible_hostname }}" != "{{ master_node }}"

#- name: Stop stolon master
# when: "{{ ansible_hostname }}" == "{{ master_node }}"

#- name: Recreate directory
# when: "{{ ansible_hostname }}" == "{{ master_node }}"

#- name: Untar backup
  # when: "{{ ansible_hostname }}" == "{{ master_node }}"

#- name: Untar wal
  # when: "{{ ansible_hostname }}" == "{{ master_node }}"

#- name: Start stolon master
  # when: "{{ ansible_hostname }}" == "{{ master_node }}"

#- name: Start stolon slaves
  # when: "{{ ansible_hostname }}" != "{{ master_node }}"

#- name: Restore roles
 # when: "{{ ansible_hostname }}" == "{{ master_node }}"

#- name: Restore dblinks
 # when: "{{ ansible_hostname }}" == "{{ master_node }}"
