---
- name: Get current master 
  command: stolonctl status --cluster-name {{ cluster_name }}  --store-backend consul --store-endpoints {{ store_endpoint }} -f json 
  register: stolon_output

- debug: 
  msg: "{{ stolon_output.cluster.master_keeper_uid }}"

- name: Set master
  set_fact: stolon_master = "stolon_output.stdout"

- name: Download backup
# when: "{{ ansible_hostname }}" == "{{ master_node }}"

- name: Dump roles
# when: "{{ ansible_hostname }}" == "{{ master_node }}"
- name: Dump db_links
# when: "{{ ansible_hostname }}" == "{{ master_node }}"

- name: Stop stolon slaves
# when: "{{ ansible_hostname }}" != "{{ master_node }}"

- name: Stop stolon master
# when: "{{ ansible_hostname }}" == "{{ master_node }}"

- name: Recreate directory
# when: "{{ ansible_hostname }}" == "{{ master_node }}"

- name: Untar backup
  # when: "{{ ansible_hostname }}" == "{{ master_node }}"

- name: Untar wal
  # when: "{{ ansible_hostname }}" == "{{ master_node }}"

- name: Start stolon master
  # when: "{{ ansible_hostname }}" == "{{ master_node }}"

- name: Start stolon slaves
  # when: "{{ ansible_hostname }}" != "{{ master_node }}"

- name: Restore roles
 # when: "{{ ansible_hostname }}" == "{{ master_node }}"

- name: Restore dblinks
 # when: "{{ ansible_hostname }}" == "{{ master_node }}"
