---

- name: Git clone pg_wait_sampling.
  git: 
    repo: https://github.com/postgrespro/pg_wait_sampling.git
    dest: /tmp/pg_wait_sampling
    update: yes

#- name: Params.
#  make:
#    chdir: /tmp/pg_wait_sampling
#    target: all
#    params:
#      USE_PGX: 1

- debug: msg="{{ ansible_env.PATH }}"
  #environment:
  #  PATH: "{{ ansible_env.PATH }}:/usr/pgpro-{{ postgresql_version }}/bin"

- name: make install
  shell: make USE_PGX=1 && make USE_PGX=1 install
  environment:
    PATH: $PATH:/usr/pgpro-{{ postgresql_version }}/bin

#- name: Make pg_wait_sampling.
#  make:  
#    chdir: /tmp/pg_wait_sampling
#    params:
#      USE_PGX: 1
#  environment:
#    PATH: $PATH:/usr/pgpro-{{ postgresql_version }}/bin

#- name: Install pg_wait_sampling.
#  make:  

#    chdir: /tmp/pg_wait_sampling
#    target: install    
#    params:
#      USE_PGX: 1

...
