---

- name: Git clone pg_wait_sampling.
  git: 
    repo: https://github.com/postgrespro/pg_wait_sampling.git
    dest: /tmp/pg_wait_sampling
    update: yes

- name: Make pg_wait_sampling. NOT YET WORKING
  make:  
   chdir: /tmp/pg_wait_sampling
   params:
    USE_PGX: 1
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/pgpro-{{ postgresql_version }}/bin"

- name: Install pg_wait_sampling.
  make:  
    chdir: /tmp/pg_wait_sampling
    target: install    
    params:
      USE_PGX: 1

...
