- include: repos.yml

- name: Installing packages
  yum: name={{ item }}
  with_items:
      - vim
      - open-vm-tools
      - wget
      - iftop
      - iotop
      - sysstat
      - hdparm
      - atop
      - lshw
      - tmux
      - mailx
      - strace
      - python-pip
      - git
      - ntp
      - mlocate
      - glances

# can we redo it in systemctl module?
- name: Set multi-user as default target
  shell: systemctl set-default multi-user.target

- name: Set multi-user a
  shell: systemctl isolate multi-user.target

- name: Sync time
  shell: ntpdate dc3
  ignore_errors: yes
