- include: repos.yml
  tags: preconf

- include: hostname.yml
  tags: preconf

- include: packages.yml
  tags: preconf

- include: targets.yml
  tags: preconf

# move to ntp role
- name: set timezone
  timezone:
    name: "{{ t_zone }}"
  tags: preconf

- name: Sync time
  shell: ntpdate dc3
  ignore_errors: yes
  tags: preconf
