- name: Import epel key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 



- name: Install EPEL Centos
  yum:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - epel-release
  when: ansible_distribution == 'CentOS'

- name: Install EPEL OL
  yum:
    state: present 
    pkg: "{{ item }}"
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
  when: ansible_distribution == 'OracleLinux'

- name: Installing packages
  yum: name={{ item }}
  with_items:
      - vim
      - open-vm-tools
      - wget
      - iftop
      - iotop
      - sysstat
      - hdparm
      - atop
      - lshw
      - tmux
      - python-pip
      - git
      - ntp
      - mlocate

- shell: systemctl set-default multi-user.target
- shell: systemctl isolate multi-user.target

- name: Sync time
  shell: ntpdate dc3
  ignore_errors: yes
