- name: Install epel
  yum:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - epel-release

- name: Installing packages
  yum: name={{ item }}
  with_items:
      - vim
      - wget
      - iftop
      - iotop
      - sysstat
      - hdparm
      - atop
      - lshw
      - tmux
      - python-pip
      - git
      - ntp
      - mlocate

- shell: systemctl set-default multi-user.target
- shell: systemctl isolate multi-user.target

- name: Sync time
  shell: ntpdate dc3
  ignore_errors: yes
