---
# defaults file for haproxy
haproxy:
  frontend_ip: {{ansible_default_ipv4.address}}
  maxconns: 4096
  backlog: 2
  timeout_q: 400ms
  timoutconnect: 5000ms
  timeoutclient: 5000ms
  timoutserver: 5000ms
  http_timeout: 15s
  balance: leastconn
  frontend_port: 83
