---
- name: Install PostgreSQL packages
  yum:
    state: present
    name:
      - postgresql{{ postgresql_version | replace('.', '') }}
      - postgresql{{ postgresql_version | replace('.', '') }}-server
      - postgresql{{ postgresql_version | replace('.', '') }}-contrib
      - postgresql{{ postgresql_version | replace('.', '') }}-libs
      - python-psycopg2
      - python3-psycopg2
      - pg_stat_kcache{{ postgresql_version | replace('.', '') }}
      - powa_{{ postgresql_version | replace('.', '') }}
      - powa_{{ postgresql_version | replace('.', '') }}-web
      - pg_qualstats{{ postgresql_version | replace('.', '') }}
      - hypopg_{{ postgresql_version | replace('.', '') }}
      - gcc
      - python3-devel
      - python3-pip
      - python3-setuptools

- name: Install Patroni with dependencies
  pip:
    name:
      - "patroni[consul]"
    state: present
    executable: pip3
  environment:
    HTTP_PROXY: "{{ lookup('env', 'http_proxy') }}"
    HTTPS_PROXY: "{{ lookup('env', 'http_proxy') }}"
