---
- import_tasks: repository.yml
  tags: repository

- import_tasks: install.yml
  tags: install

- import_tasks: security.yml
  tags: security

- import_tasks: setup.yml
  tags: setup

- import_tasks: check.yml
  tags: check

#  getting output.json from check task, thus neet to run in first
- import_tasks: powa.yml
  when: "output.json.role == 'master'"
  tags: powa
