galaxy_info:
  author: "Daniil Aksenov"
  description: Setup basic PostgreSQL 9.x configurations on RedHat/CentOS/Scientific/Oracle Enterprise Linux.
  license: as-is
  platforms:
    - name: EL
      versions:
      - 7
  categories:
   - database
   - database:sql
