---
 
- name: Install pgbadger and httpd.
  yum:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - pgbadger
    - httpd

- name: Start httpd service.
  service:
    name: httpd
    state: started
    enabled: yes

- name: Create apache badger directory.
  file:
    path: /var/www/badger
    owner: postgres
    group: postgres
    state: directory
    mode: 0755

- name: Add firewall exception for http. Ignore if firewall is off.
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes

- name: Place config for badger site.
  template:
    src: http.conf
    dest: /etc/httpd/conf.d/badger.conf
  notify:
    - restart httpd 

- name: Configure cron for badger.
  cron:
    name: "pgbadber daily"
    user: postgres
    minute: "50"
    hour: "23"
    job: "pgbadger -Z '+03' --quiet --retention 4 -I -O /var/www/badger/ {{ pg_data }}/pg_log/postgresql*.log &>/tmp/pgbadger.log"

...
