---

- name: "Install additional postgresql tools."
  yum: 
    state: latest
    pkg: "{{ item }}"
  with_items:
    - pgcenter
    # python-devel requered for pgcli
    - python-devel

- name: "Install pgcli command shell."
  pip:
    name: pgcli
   
...
