---

- name: config file for new backup client
  template:
    src: pg_server.conf.y2 
    dest: "/etc/barman.d/{{ pg_server }}.conf"
    owner: root
    group: root
    mode: '0644'

- name: add new server to pgpass
  lineinfile:
    path: /var/lib/barman/.pgpass
    state: present
    line: '"{{ pg_server }}":5432:postgres:barman:barman:barman'

- name: add new server to pgpass
  lineinfile:
    path: /var/lib/barman/.pgpass
    state: present
    line: '"{{ pg_server }}":5432:postgres:barman:streaming_barman:barman'

...
