---

- name: config file for new backup client
  template:
    src: pg_server.conf.y2 
    dest: "/etc/barman.d/{{ pg_server }}.conf"
    owner: root
    group: root
    mode: '0644'

- name: add new server to pgpass
  lineinfile:
    path: /var/lib/barman/.pgpass
    state: present
    line: '"{{ pg_server }}":5432:postgres:barman:barman:barman'

- name: add new server to pgpass
  lineinfile:
    path: /var/lib/barman/.pgpass
    state: present
    line: '"{{ pg_server }}":5432:postgres:barman:streaming_barman:barman'

# add new backup job to cron
# crontab -l > /tmp/cron.tmp
# echo "0 1 * * * barman backup $pg_host &>/var/lib/barman/log/backup_$pg_host.log" >> /tmp/cron.tmp
# crontab /tmp/cron.tmp
# rm /tmp/cron.tmp

...

