---

- name: Reminder
  debug:
     msg: postgresql server name should be supplied via --extra-vars "pg_server="

- name: config file for new backup client
  template:
    src: pg_server.conf.j2 
    dest: "/etc/barman.d/{{ ansible_hostname }}.conf"
    owner: root
    group: root
    mode: '0644'

- name: Add barman's password pgpass.
  lineinfile:
    dest: "/var/lib/barman/.pgpass"
    state: present
    line: '{{ ansible_hostname }}:5432:postgres:barman:{{ barman_password }}'

- name: Add streaming_barman password to pgpass.
  lineinfile:
    dest: "/var/lib/barman/.pgpass"
    state: present
    line: '{{ ansible_hostname }}:5432:postgres:streaming_barman:{{ streaming_barman_password }}'

- name: Create replication slot.
  shell: barman receive-wal --create-slot "{{ ansible_hostname }}"
  become: yes
  become_user: barman

...
