---

- name: add barman user pub_key
  authorized_key: user=postgres key="{{ lookup('file', '/home/dbax/localrepo/barman_key') }}"

- name: Add barman db user.
  postgresql_user:
    name: barman
    password: "{{ barman_password }}"
    role_attr_flags: SUPERUSER
  become_user: postgres   

- name: Add barman_streaming db user.
  postgresql_user:
    name: streaming_barman
    password: "{{ streaming_barman_password }}"
    role_attr_flags: SUPERUSER,REPLICATION
  become_user: postgres   

- name: Edit hba.conf for barman.
  lineinfile: dest=/var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf line='host all barman {{ barman_server  }} md5'
  tags: barman_hba 

- name: Edit hba.conf for streaming_barman. Can it be redone with md5?
  lineinfile: dest=/var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf line='host replication streaming_barman {{ barman_server  }} trust'
  tags:  barman_hba

- name: Reminder
  debug:
      msg: PostgreSQL WAL archiving and replication is in initial postgres config role.

- name: Create directory for postgresql scripts
  file: 
    path: /var/lib/pgsql/scripts
    state: directory
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"

- name: Copy cleanup script. 
  template:
    src: archivecleanup.sh.j2
    dest: /var/lib/pgsql/scripts/archivecleanup.sh
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0700

- name: Configure cron for archivecleanup.
  cron:
    user: "{{ postgresql_admin_user }}"
    name: "archive_cleanup"
    minute: "0"
    hour: "2"
    job: "/var/lib/pgsql/scripts/archivecleanup.sh &>/tmp/archivecleanup.log"

...
