---

- name: add barman user pub_key
  authorized_key: user=postgres key="{{ lookup('file', '/home/dbax/localrepo/barman_key') }}"

- name: add barman db user
  postgresql_user:
    name: barman
    password: "{{ barman_password }}"
    role_attr_flags: SUPERUSER
  become_user: postgres   

- name: add barman streaming db user
  postgresql_user:
    name: streaming_barman
    password: "{{ streaming_barman_password }}"
    role_attr_flags: SUPERUSER,REPLICATION
  become_user: postgres   

# to do: add pg_hba on target! move this to postgres role?
#host    all             barman    {{ barman_server  }}/24     md5
#host replication streaming_barman {{ barman_server  }}/24 trust

- name: Reminder
  debug:
      msg: PostgreSQL WAL archiving and replication is in initial postgres config role.

...
