- name: add barman user pub_key
  authorized_key: user=postgres key="{{ lookup('file', '/home/dbax/localrepo/barman_key') }}"

- name: add barman db user
  postgresql_user:
    name: barman
    password: {{ barman_password }}
    role_attr_flags: SUPERUSER

- name: add barman streamin db user
  postgresql_user:
    name: streaming_barman
    password: {{ streaming_barman_passwordi }}
    role_attr_flags: SUPERUSER,REPLICATION

# to do: add pg_hba on target!
#host    all             barman              10.197.72.152/24     md5
#host replication streaming_barman 10.197.72.152/24 trust

# PostgreSQL WAL archiving and replication postgresql.conf
# ssh postgres@$pg_host sed -i -e "s/#wal_level = 'minimal'/wal_level = 'hot_standby'/g" /var/lib/pgsql/*/data/postgresql.conf
# ssh postgres@$pg_host sed -i -e "s/#max_wal_senders = 0/max_wal_senders = 2/g" /var/lib/pgsql/*/data/postgresql.conf
# ssh postgres@$pg_host sed -i -e "s/#max_replication_slots = 0/max_replication_slots = 2/g" /var/lib/pgsql/*/data/postgresql.conf
