--- 

- name: Configure firewall. Ingnore if service is not running. Or turn in on?
  firewalld: service=postgresql permanent=true state=enabled
  ignore_errors: yes

- name: Find if pg cluster already exists.
  find: paths="/var/lib/pgsql/{{ postgresql_version }}/data/" file_type=file patterns="PG_VERSION"
  register: pg_dir

- name: Initialize new postgresql cluster in default directory. If not already exists.
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  command: "/usr/pgsql-{{ postgresql_version }}/bin/initdb -D /var/lib/pgsql/{{ postgresql_version }}/data"
  when: pg_dir.matched|int == 0

- name: Start and enable postgresql service.
  service: 
    name: "postgresql-{{ postgresql_version }}" 
    state: started 
    enabled: yes

...
