---

- include: configure.yml
  tags: 3_configure

- include: postgresql_conf.yml
  tags: postgresql_conf

#- include: postgresql_log_conf.yml
#  tags: postgresql_log_conf

- include: pg_hba_conf.yml
  tags: pg_hba_conf

- include: extensions.yml
  tags: pg_extensions

...
