--- 
#as separate role and parameters as dict to be included as shown at https://github.com/galaxyproject/ansible-postgresql
- name: Modify postgresql.conf shared fuffers 
  lineinfile:
      dest: "{{ pg_data }}/postgresql.conf"
      regexp: "^#?shared_buffers ="
      line: "shared_buffers = {{ (ansible_memory_mb.real.total/4) |round|int }}MB"
  notify: restart postgres
