---

- name: Install open VM tools for VMWARE.
  yum: 
     name={{ item }} state=latest
  with_items:
   - open-vm-tools

- name: VmWare service start and enabling.
  service: 
     name: vmtoolsd.service 
     state: started 
     enabled: yes

...
