---

- name: Reminder.
  debug:
     msg: Dependencies in playbook not working correctly(ansible issue 13406). Need to install oracle clent by hands!

- name: Git clone oraclefdw. 
  git: repo=https://github.com/laurenz/oracle_fdw
       dest=~/src/oracle_fdw
       update=yes

- name: Make oracle_fdw.
  shell: make && make install 
  args:
    chdir: ~/src/oracle_fdw

- name: Create extension.
  postgresql_ext: 
    name: oracle_fdw
    db: postgres
  become_user: postgres

...
