---
- name: Install yum-cron.
  become: yes
  yum:
    name: yum-cron
    state: latest

- name: Copy the configuration file (CentOS 7).
  become: yes
  template:
    src: etc/yum/yum-cron.conf.j2
    dest: /etc/yum/yum-cron.conf
  notify:
    - restart yum-cron
  when: ansible_distribution_version >= 7

- name: Start yum-cron.
  become: yes
  service:
    name: yum-cron
    state: started
    enabled: yes
