---

- name: Install barman software.
  yum:
    state: latest
    
    name:
    - barman

# Configure barman user. pg_receivexlog to PATH

- name: Barman sever. Config file for new backup client
  template:
    src: pg_server.conf.j2 
    dest: "/etc/barman.d/{{ ansible_hostname }}.conf"
    owner: root
    group: root
    mode: '0644'

- name: Barman sever. Add barman password pgpass.
  lineinfile:
    dest: "/var/lib/barman/.pgpass"
    create: yes
    owner: barman
    group: barman
    mode: '0600'

    state: present
    line: '{{ ansible_hostname }}:5432:postgres:barman:{{ barman_password }}'

- name: Barman sever. Add streaming_barman password to pgpass.
  lineinfile:
    dest: "/var/lib/barman/.pgpass"
    state: present
    line: '{{ ansible_hostname }}:5432:postgres:streaming_barman:{{ streaming_barman_password }}'

...
