---

- name: Set zabbix-agent name. If no domain name defined.
  set_fact:
     agent_name: "{{ inventory_hostname }}"   
     when: ansible_dns.search[0] is undefined

- name: Set zabbix-agent name. If domain name defined.
  set_fact:
     agent_name: "{{ inventory_hostname }}.{{ ansible_dns.search[0] }}"   
     when: ansible_dns.search[0] is defined
  ignore_errors: True

- include: install.yml
  tags: mamonsu
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ inventory_hostname }}.{{ ansible_dns.search[0] }}"
    - "{{ inventory_hostname }}"
  name: agent_name 

- include: zabbix_register.yml
  agent_name: "{{ agent_name }}"
  tags: mamonsu-register
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ inventory_hostname }}.{{ ansible_dns.search[0] }}"
    - "{{ inventory_hostname }}"
  name: agent_name 


...
