---

- name: Installing nfs packages
  yum: 
    name:
      - nfs-utils

- name: Mount backup share.
  mount:
    path: /mnt/barman
    src: 192.168.155.224:/var/lib/pgsql/dumps
    fstype: nfs
    opts: rw
    state: mounted

...
