---
- name: prepare
  hosts: all
  vars:
    postgresql_version: 12
  tasks:
    - name: Install sudo(is absent in centos 8 docker image by default)
      dnf:
        name: sudo
        state: present
  roles:
    - role: proxy_settings
    - role: anacron
    - role: postgresql