# move to another role?
- name: Installing prereqs
  yum: name={{ item }}
  with_items:
      - git
      - make 
      - rpm-build 
      - python2-devel 
      - libselinux-python
      - python-setuptools
  tags: mamonsu

- name: git clone mamonsu 
  git: repo=https://github.com/postgrespro/mamonsu
       dest=~/src/mamonsu
       update=yes
  tags: mamonsu

- name: make rpm from source
  shell: make rpm 
  args:
    chdir: ~/src/mamonsu
  tags: mamonsu

- name: install mamonsu from local file
  shell: yum localinstall -y mamonsu*.rpm
  args:
    chdir: ~/src/mamonsu
  tags: mamonsu

- name: Copy agent.conf template 
  template: owner=root group=root mode=644 
            src=agent.conf
            dest=/etc/mamonsu/agent.conf
  notify:
    - restart mamonsu
  tags: mamonsu

# Redo user and db create with ansible postgres module
- name: Bootstrap DDL for monitoring
  shell: createdb mamonsu && createuser mamonsu && mamonsu bootstrap -U postgres -d mamonsu
  become: true
  become_user: postgres
  ignore_errors: yes
  tags: mamonsu

- name: start monitoring service.
  service: name=mamonsu state=restarted enabled=yes

