# move to another role?
- name: Installing prereqs
  yum: name={{ item }}
  with_items:
      - git
      - make 
      - rpm-build 
      - python2-devel 
      - libselinux-python
      - python-setuptools

- name: git clone mamonsu 
  git: repo=https://github.com/postgrespro/mamonsu
       dest=~/src/mamonsu
       update=yes

- name: make rpm from source
  shell: make rpm 
  args:
    chdir: ~/src/mamonsu

- name: install mamonsu from local file
  shell: yum localinstall -y mamonsu*.rpm
  args:
    chdir: ~/src/mamonsu

- name: Copy agent.conf template 
  template: owner=root group=root mode=644 
            src=agent.conf
            dest=/etc/mamonsu/agent.conf

#- lineinfile: dest=/etc/mamonsu/agent.conf regexp='address' line='address = 192.168.154.145'
#- lineinfile: dest=/etc/mamonsu/agent.conf regexp='client' line='client = {{ ansible_hostname }}'
#- lineinfile: dest=/etc/mamonsu/agent.conf regexp='user' line='user = mamonsu'
#- lineinfile: dest=/etc/mamonsu/agent.conf regexp='database' line='database = mamonsu'

# Bootstrap DDL for monitoring (if you want to monitoring without superuser rights)
# Redo user and db create with ansible postgres module
- name: Bootstrap DDL for monitoring
  shell: createdb mamonsu && createuser mamonsu && mamonsu bootstrap -U postgres -d mamonsu
  become: true
  become_user: postgres
  ignore_errors: yes

#- name: start monitoring service. systemd module will be supported in 2.5
#- service: name=mamonsu state=restarted enabled=yes
#- shell: systemctl enable mamonsu
#- shell: systemctl start mamonsu

# redo as handler?
- systemd: 
    name: mamonsu 
    enabled: yes 
    state: started
