---
- name: Install mamonsu repo
  yum:
    state: present 
    name: https://repo.postgrespro.ru/mamonsu/keys/mamonsu-repo-centos.noarch.rpm
  tags: slave

- name: Install mamonsu(pip)
  yum:
    name: mamonsu
    state: present
  tags: slave

- name: Copy agent.conf template
  template:
    owner: root
    group: root
    mode: 0644
    src: mamonsu_agent.conf.j2
    dest: /etc/mamonsu/agent.conf
  notify:
    - restart mamonsu
  tags: slave

- name: Create mamonsu database user
  postgresql_user:
    name: mamonsu
    port: "{{ postgresql_port }}"
  become_user: postgres
  become: true

- name: Create Mamonsu database.
  postgresql_db:
    name: mamonsu
    state: present
    port: "{{ postgresql_port }}"
    owner: mamonsu
  become_user: postgres
  become: true

- name: Start monitoring service.
  service:
    daemon_reload: true
    name: mamonsu
    state: started
    enabled: true
  tags: slave