---

- name: reload postgres
  service: name=postgresql-{{ postgresql_version }} state=reloaded

- name: restart postgres
  service: name=postgresql-{{ postgresql_version }} state=restarted

...
