---

- name: Ensure ntpd installed.
  yum: name={{ item }}
  with_items:
      - ntpdate
      - ntp

- name: Set timezone.
  timezone:
    name: "{{ t_zone }}"

- name: Enshure ntpd is stopped for successfull initial sync.
  service: name=ntpd state=stopped enabled=yes

- name: Sync time.
  shell: ntpdate {{ ntp_server }} 
  ignore_errors: yes

- name: Start and enable ntpd service.
  service: name=ntpd state=started enabled=yes  

...
