---

- name: set timezone
  timezone:
    name: "{{ t_zone }}"

- name: Sync time
  shell: ntpdate dc3
  ignore_errors: yes

- name: Start and enable ntpd service.
  service: name=ntpd state=started enabled=yes  

...
