---

- name: Ensure ntpd installed.
  yum: name={{ item }}
  with_items:
      - ntpdate
      - ntp

- name: Set timezone.
  timezone:
    name: "{{ t_zone }}"

- name: Copy config from template
  template:
    src: ntp.conf.j2
    dest: "/etc/ntp.conf"
    owner: root
    group: root
    mode: 0644
  backup: yes
  notify:
    - restart ntpd

- name: Start and enable ntpd service.
  service: name=ntpd state=started enabled=yes  

...
