---
- name: Install pgbouncer
  yum:
    state: present
    name:
      - pgbouncer

- name: Copy pgbouncer.ini template.
  template:
    owner: root
    group: root
    mode: 0644
    backup: true
    src: pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
  notify:
    - reload pgbouncer

- name: Copy userlist template
  template:
    owner: root
    group: root
    mode: 0644
    src: userlist.txt.j2
    dest: /etc/pgbouncer/userlist.txt
    backup: true
  notify:
    - reload pgbouncer

- name: Add firewall exception. If firewall is on.
  firewalld:
    port: "{{ pgbouncer_conf.listen_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true

- name: Start pgbouncer
  service:
    name: pgbouncer
    state: started
    enabled: true
