---
- name: Create /etc/patroni
  file:
    state: directory
    dest: /etc/patroni

- name: Create /var/log/patroni
  file:
    state: directory
    owner: postgres
    group: postgres
    dest: /var/log/patroni
  when: patroni_log_dir is defined
  
- name: Create patroni systemd service
  template:
    src: patroni.service.j2
    dest: "/etc/systemd/system/patroni.service"
    owner: root
    group: root
    backup: true
    force: true
    mode: 0644
  # when install from package manager, systemd service created automatically
  when: ansible_pkg_mgr != "apt"

- name: Create patroni config file from template
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    backup: true
  notify:
    - reload patroni

- name: Start and enable patroni
  systemd:
    name: patroni
    state: started
    enabled: true
    daemon_reload: true