---
- name: Add repository gpg key. 
  rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgresql_version }}

- name: Add PostgreSQL repository. 
  yum_repository:
    name: "pgdg{{ postgresql_version }}"
    description: "Postgresql{{ postgresql_version }} repository."
    baseurl: https://download.postgresql.org/pub/repos/yum/{{ postgresql_version }}/redhat/rhel-$releasever-$basearch
    enabled: yes
    gpgcheck: yes 

# to be removed?
- name: Add postgres-pro repository.
  yum_repository:
     name: "postgrespro-{{ postgresql_version }}"
     description: "postgrespro-{{ postgresql_version }}"
     baseurl: http://repo.postgrespro.ru/pgpro-{{ postgresql_version }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/os/x86_64/rpms
     #baseurl: http://repo.postgrespro.ru/pgpro-{{ postgresql_version }}/keys/postgrespro-{{ postgresql_version }}.rhel.pro.yum-1.0-1.noarch.rpm
     #gpgkey: https://packagecloud.io/postgrespro/mamonsu/gpgkey
     gpgcheck: no
     enabled: yes
  when: postgresql_distribution == 'postgrespro'
