---
- import_tasks: configure.yml
  tags: 3_configure

# to separate role
- import_tasks: postgresql_conf.yml
  tags: postgresql_conf

- import_tasks: pg_hba_conf.yml
  tags: pg_hba_conf

- import_tasks: pg_buffercache.yml
  tags: pg_extensions

- import_tasks: pg_stat_statements.yml
  tags: pg_extensions
