---

- name: Add Ceph deploy user.
  user: name="{{ ceph_deploy_user }}"
        createhome=yes
        home="/home/{{ ceph_deploy_user }}"
        state=present
        generate_ssh_key=yes

- name: Get public key.
  fetch:
    src: /home/{{ ceph_deploy_user }}/.ssh/id_rsa.pub
    dest: /tmp/ceph_pub_key
    validate_checksum: yes
  host: "{{ ceph-deploy-server }}"

- name: Add ceph_deploy_user pub_key.
  authorized_key: user=postgres key="{{ lookup('file', '~/localrepo/ceph-deploy-key') }}"

...