---

- name: Add Ceph deploy user.
  user: name="{{ ceph_deploy_user }}"
        groups=wheel
        createhome=yes
        home="/home/{{ ceph_deploy_user }}"
        state=present
        generate_ssh_key=yes

#- name: Get public key.
#  fetch:
#    src: /home/{{ ceph_deploy_user }}/.ssh/id_rsa.pub
#    dest: /tmp/ceph_pub_key
#    validate_checksum: yes
#    host: "{{ ceph-deploy-server }}"

- name: Add ceph_deploy_user pub_key.
  authorized_key: user={{ ceph_deploy_user }} key="{{ lookup('file', '~/localrepo/ceph-deploy-key') }}"

- name: Configure sudoers.
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ ceph_deploy_user }}"
    owner: root
    group: root
    mode: 0644
    validate: 'visudo -cf %s'

- name: http_proxy
  lineinfile: dest=/home/{{ ceph_deploy_user }}/.bash_profile regexp='http_proxy' line='export http_proxy={{ proxy_ip }}'
  tags: proxy_bash_profile

- name: https_proxy
  lineinfile: dest=/home/{{ ceph_deploy_user }}/.bash_profile regexp='https_proxy' line='export https_proxy={{ proxy_ip }}'
  tags: proxy_bash_profile

         
...