---

- name: Create directory for tomcat stuff.
  file:
    path: "{{ tomcat_dir }}/logs" 
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0755

- name: Copy tomcat from local repo.
  copy: src={{ item }}
        dest=/tmp
  with_items:
        - ~/localrepo/apache-tomcat-8.5.23.tar.gz
        
- name: Untar tomcat. 
  unarchive:
    src: "/tmp/apache-tomcat-8.5.23.tar.gz"
    dest: "{{ root_dir }}"
    remote_src: True
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0755

- name: Create systemd file for tomcat.
  template:
    src: tomcat.service.j2
    dest: "/etc/systemd/system/tomcat.service"
    owner: root
    group: root
    force: yes
    mode: 0644

- name: Setup tomcat manager interface (tomcat_users).
  template:
    src: tomcat_users.j2
    dest: "{{ tomcat_dir }}/conf/tomcat-users.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    force: yes
    mode: 0644

- name: Setup tomcat manager interface (manager context).
  template:
    src: manager_context.j2
    dest: "{{ tomcat_dir }}/webapps/manager/META-INF/context.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    force: yes
    mode: 0644

- name: Add firewall exception. If firewall is on.
  firewalld: port=8080/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
    
- name: Start and enable tomcat.
  systemd:
    state: started
    name: tomcat
    daemon_reload: yes
    enabled: yes

...
