---

- name: Ensure cluster group membership.
  fail: msg="Cluster hosts must be members of a group"
  when: pacemaker_ansible_group is not iterable

- name: Installing packages.
  yum: name={{ item }}
  with_items:
      - pacemaker
      #- resource-agents
      - pcs
      #- fence-agents-all
      #- fence-agents-virsh 

- name: Disable selinux.
  selinux: policy=targeted state=disabled

- name: Configure firewall.
  firewalld: service=high-availability permanent=true state=disabled 

- name: Ensure corosync is disabled and stopped.
  service: name=corosync enabled=no state=stopped
  
- name: Ensure pacemaker is disabled and stopped.
  service: name=pacemaker enabled=no state=stopped

- name: Set the password for the cluster user.
  user:
    name={{ pacemaker_user }}
    password={{ pacemaker_password | password_hash('sha512', ansible_hostname) }}

- name: Ensure pcsd enabled and started.
  service: name=pcsd enabled=yes state=started

- debug: msg="play_hosts={{play_hosts}}"
  run_once: true

# Whats this for? no such in https://wiki.clusterlabs.org/wiki/PgSQL_Replicated_Cluster.
- name: Authenticate all nodes. This is not working yet.
  command: >
    pcs cluster auth
    {% for host in groups[pacemaker_ansible_group] %}
    {{ hostvars[host]['ansible_hostname'] }}
    {% endfor %}
    -u {{ pacemaker_user }} -p {{ pacemaker_password }}
  run_once: true
  args:
    creates: /var/lib/pcsd/tokens

- name: Setup cluster message bus
  run_once: true
  command: >
    pcs cluster setup --name {{ pacemaker_cluster_name }}
    {% for host in groups[pacemaker_ansible_group] %}
    {{ hostvars[host]['ansible_hostname'] }}
    {% endfor %}
  args:
    creates: /etc/corosync/corosync.conf

...
