---
- name: Installing vim
  yum:
    name:
      - vim

- name: Setup vimrc as template.
  template:
    src: vimrc.j2
    dest: "/home/{{ my_ansible_user }}/.vimrc"
    owner: "{{ my_ansible_user }}"
    group: "{{ my_ansible_user }}"
    mode: 0600

