- name: "install repository package"
  shell: yum localinstall -y http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
  #yum: 
  #  state: present
  #  name: http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm

- name: "install zabbix-agent"
  yum: 
    state: latest
    pkg: "{{ item }}"
  with_items:
    - zabbix-agent

#name: "edit agent.conf file"
- lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server=*' line='Server=192.168.154.145'
- lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=*' line='Hostname={{ ansible_hostname }}'

- name: "start agent"
  service: name=zabbix-agent state=started enabled=yes 

- name: add firewall exception
  firewalld: port=10050/tcp permanent=true state=disabled 
