---

- name: Add my additional admin user.
  user: name: "{{ my_admin_user }}"
        groups: wheel
        createhome: yes
        home: "/home/{{ my_admin_user }}"
        generate_ssh_key: yes
        state: present

- name: Add my users pub_key.
  authorized_key: 
        user: {{ my_admin_user }}
        key: "{{ lookup('file', '/home/{{ my_admin_user }}/.ssh/id_rsa.pub') }}"

- name: Add my ansible user pub_key from Windows.
  authorized_key:
        user: {{ my_admin_user }}
        key: "{{ lookup('file', '/home/{{ my_ansible_user }}/localrepo/my_key_win') }}"

- name: configure sudoers
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ my_admin_user }}"
    owner: root
    group: root
    mode: 0644
    validate: 'visudo -cf %s'

...
