# file: roles/install-postgresql-on-el6/tasks/install.yml -- install postgresql packages

- name: Add repository
  yum_repository:
    name: pgdg 
    description: Postgresql {{ postgresql_version}} repository
    baseurl: https://yum.postgresql.org/{{ postgresql_version }}/redhat/rhel-7-x86_64/pgdg-{{ ansible_distribution | lower }}{{ postgresql_version | replace('.','') }}-{{ postgresql_version }}-3.noarch.rpm
#add gpgkey?

- name: "Stage 1: install postgresql packages"
  yum: 
    state: latest
    pkg: "{{ item }}"
  with_items:
    - postgresql{{ postgresql_version | replace('.', '') }}-server

- name: "Stage 1: install postgresql contrib package"
  yum: 
    state: latest
    pkg: postgresql{{ postgresql_version | replace('.', '') }}-contrib
  when: postgresql_contrib

- name: Update alternatives
  shell: ls /usr/pgsql-{{ postgresql_version }}/bin/ | grep -v postmaster | xargs -I{} sudo update-alternatives --install /usr/bin/{} pgsql-{}  /usr/pgsql-{{ postgresql_version }}/bin/{} {{ postgresql_version | replace('.', '') }}0
