---

- name: Edit yum.conf.
  lineinfile: 
      dest: /etc/yum.conf
      regexp: '^proxy'
      line: 'proxy={{ proxy_ip }}'
  tags: proxy_yum
  when: proxy_ip is defined

# Proxy can be set on play level, thus rest not needed
#- import_tasks: proxy_git.yml
 
#- import_tasks: proxy_wget.yml

#- import_tasks: proxy_bash_profile.yml

...
