---
- import_tasks: repos.yml
  tags: repos

#- import_tasks: hosts.yml
#  tags: hosts

- import_tasks: packages.yml
  tags: packages-misc

- import_tasks: packages-mon.yml
  tags: packages-mon

- import_tasks: packages-net.yml
  tags: packages-net

- import_tasks: packages-dev.yml
  tags: packages-dev

- import_tasks: packages-py.yml
  tags: packages-py
  
- import_tasks: tmux.yml
  tags: tmux

#- import_tasks: targets.yml
#  tags: runlevels
