---
- name: Installing network tools.
  yum:
    name:
      - net-tools
      - iptraf
      - nethogs
      - tcpdump
      - iperf
      - mtr
      - iftop
      - wget
      - ntpdate
      - ngrep
      - bind-utils
      - traceroute
      - nload
      - fping
