---

- name: Installing monitoring tools.
  yum:
    name:
      - hdparm
      - iotop
      - sysstat
      - htop
      - lshw
      - strace
      - lsof
      # Uilities for the proc filesystem fuser, killall, pidof, pstree
      - psmisc
      # tools and drivers for monitoring temperatures, voltage, and fans
      - lm_sensors

- name: Installing lnav logfile broweer for Centos 7
  # Unable to find it on Centos 8
  yum:
    name:
      - lnav
  when: ansible_distribution_major_version|int == 7

