---

- name: Installing packages
  yum: name={{ item }}
  with_items:
      # DEV tools
      - git
      - gcc
      - make
      - rpm-build
      - gdb 
      
      # PY tools
      - python-pip 
      - python-devel
      - python-setuptools
      - libselinux-python
      
      # MON tools
      - hdparm
      - iotop
      - sysstat
      # I have special role for atop, let be here just in case.
      - atop
      - htop
      # Logfile browser
      - lnav
      - lshw
      - strace
      - glances
      - lsof
      # A set of utilities that use the proc filesystem (fuser, killall, pidof, pstree).
      - psmisc
      # tools and drivers for monitoring temperatures, voltage, and fans.
      - lm_sensors
      
      # MISC tools
      - vim
      - open-vm-tools
      # Database for local files
      - mlocate
      # I have special role for tmux, let it be here just in case.
      - tmux
      - rsync
      - zip
      - unzip
      - tree
   
      # Network tools
      - net-tools
      - iptraf    
      - nethogs
      - tcpdump
      - iperf
      - mtr
      - iftop
      - wget
      - ntpdate      
      - ngrep
      - bind-utils
      - traceroute
        
...
