---
- name: Installing misc packages
  yum:
    state: present
    name:
      - vim
      # Database for local files indexing and search
      - mlocate
      - rsync
      - zip
      - unzip
      - tree
      - nfs-utils
      # gnu parallel
      - parallel
      # Used by many apps
      - java
      # bash json querying tool
      - jq
      - mc

- name: Install open-vm-tools for virtual machines.
  yum:
    state: present
    name:
      - open-vm-tools
  when: ansible_virtualization_role == 'guest'

- name: Start and enable open-vm-tools service.
  service:
    name: vmtoolsd.service
    state: started
    enabled: true
  when: ansible_virtualization_role == 'guest'
