---

- name: Installing packages
  yum: name={{ item }}
  with_items:
      - vim
      # Database for local files
      - mlocate
      - rsync
      - zip
      - unzip
      - tree
        
...