---
- name: Installing misc packages
  yum: name={{ item }}
  with_items:
      - vim
      # Database for local files indexing and search
      - mlocate
      - rsync
      - zip
      - unzip
      - tree
      - mc
      # gnu parallel
      - parallel
