---
- name: Install EPEL Centos
  yum:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - epel-release
  when: ansible_distribution == 'CentOS'

- name: Install EPEL OL
  yum:
    state: present 
    pkg: "{{ item }}"
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
  when: ansible_distribution == 'OracleLinux'

- name: Enable Optional repo on OL7
  yum_repository:
    name: ol{{ ansible_distribution_major_version }}_optional_latest 
    description: Oracle Linux $releasever Optional Latest ($basearch)
    file: public-yum-ol{{ ansible_distribution_major_version }} 
    baseurl: http://public-yum.oracle.com/repo/OracleLinux/OL{{ ansible_distribution_major_version }}/optional/latest/$basearch/ 
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
    gpgcheck: yes
    enabled: yes
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version|int >= 7
