---

- name: Installing packages.
  yum: name={{ item }}
  with_items:
      - tmux

- name: Setup tmux.conf as template. Its root for now. To be replaced in future.
  template:
    src: tmux.conf.j2
    dest: /root/.tmux.conf
    owner: root
    group: root
    mode: 0700

...
