---
zabbix_version: 4.0
zabbix_proxy: ""
zabbix_agent_register: false
zabbxi_server: 127.0.0.1
zabbix_serveractive: 127.0.0.1

zabbix_agent_conf:
  PidFile: /var/run/zabbix/zabbix_agentd.pid
  LogFile: /var/log/zabbix/zabbix_agentd.log
  LogFileSize: 0
  EnableRemoteCommands: 1
  LogRemoteCommands: 1
  Server: "{{ zabbix_server }}"
  ServerActive: "{{ zabbix_serveractive }}"
  Hostname: "{{ ansible_fqdn }}"
  Include: /etc/zabbix/zabbix_agentd.d/*.conf
