---
# Temporary solution. Need to fix this in later revision.
- name: Set zabbix-agent name. If no domain name defined.
  set_fact:
     agent_name: "{{ inventory_hostname }}"   
     when: ansible_dns.search[0] is undefined

- name: Set zabbix-agent name. If domain name defined.
  set_fact:
     agent_name: "{{ inventory_hostname }}.{{ ansible_dns.search[0] }}"   
     when: ansible_dns.search[0] is defined
  ignore_errors: True

- name: Enable mamonsu repository.
  yum_repository:
    name: postgrespro_mamonsu
    description: postgrespro_mamonsu
    baseurl: https://packagecloud.io/postgrespro/mamonsu/el/{{ ansible_distribution_major_version }}/$basearch
    #redo with rpm-key?
    gpgkey: https://packagecloud.io/postgrespro/mamonsu/gpgkey
    gpgcheck: no
    enabled: yes

- name: Install mamonsu.
  yum: 
    state: latest
    
    name:
    - mamonsu

- name: Copy agent.conf template 
  template: owner=root group=root mode=644 
            src=agent.conf
            dest=/etc/mamonsu/agent.conf
  notify:
    - restart mamonsu

# Redo user and db create with ansible postgres module
- name: Bootstrap DDL for monitoring
  shell: createdb mamonsu && createuser mamonsu && mamonsu bootstrap -U postgres -d mamonsu
  become: true
  become_user: postgres
  ignore_errors: yes
  notify:
    - restart mamonsu

- name: start monitoring service.
  service: 
     name: mamonsu
     state: started
     enabled: yes
