---
# 1 install repmgr from current repo.
- name: Install repmgr software.
  yum:
    state: latest
    
    name:
    - "repmgr{{ postgresql_version | replace('.', '')  }}"

# 2. Edit postgresql.conf

# 3. Create user and databaes for repmgr

- name: Create repmgr database user.
  postgresql_user:
    name: repmgr
    role_attr_flags: SUPERUSER

- name: Create repmgr database.
  postgresql_db:
    name: repmgr
    owner: repmgr

# 4. Правка pg_hba.conf     
# 5. On the standby, ensure the destination data directory exist and are owned by the postgres system user. 
# not needed right now. should present if pg binaries installed on previous step.

# 6. Create a repmgr.conf file on the primary server.

- name: Create repmgr config file from template.
  template:
    src: repmgr.conf.j2
    dest: "/etc/repmgr/{{ postgresql_version }}/repmgr.conf"
    owner: root
    group: root
    mode: 0644

# 7. Register the primary server

# 8. Clone the standby server
# if not already cloned

# 10. Register the standby

# SLOT?

# 11. disable postgresql systemd service
- name: Disable postgresql systemd service. Databases will be managed with pg_ctl by repmgr.
  service: 
    name: "{{ postgresql_distribution }}-{{ postgresql_version }}" 
    enabled: no
