---
- name: Disable root login. Need to redo this with template.
  lineinfile:   dest=/etc/ssh/sshd_config
                regexp="#PermitRootLogin"
                line="PermitRootLogin no"
                state=present
  notify: restart sshd

- name: Disable password authentication
  lineinfile:   dest=/etc/ssh/sshd_config
                regexp="PasswordAuthentication yes"
                line="PasswordAuthentication no"
                state=present
  notify: restart sshd

# Limit login users ?

#- name: Set firewall to prevent brute-force attacks by logging and blocking repeated attempts to login from the same IP address.
